{
 "title": "LFE域名详版",
 "tags": [
  "LFE",
  "15天数据",
  "不对外开放",
  "全量细节查询"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "entrance", "label": "流量入口", "query": "provider:aws" },
   {
    "name": "select_prod",
    "label": "产品线",
    "query": "{\"find\": \"terms\", \"field\": \"prod_type\", \"size\": 1000}"
   },
   {
    "name": "select_idc",
    "label": "数据中心",
    "query": "{\"find\": \"terms\", \"field\": \"provider\", \"orderBy\": \"doc_count\"}"
   },
   {
    "name": "select_domain",
    "label": "域名",
    "query": "{\"find\": \"terms\", \"field\": \"domain\",\"size\":10000}"
   },
   {
    "name": "select_api",
    "label": "API接口",
    "query": "{\"find\": \"terms\", \"field\": \"requestInterface\", \"query\": \"domain: $select_domain\", \"orderBy\": \"doc_count\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "域名:$select_domain--流量入口： (${entrance:raw})--(接口:$select_api)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain) AND  (requestInterface:$select_api) AND  (${entrance:raw}) NOT  (response:430)  NOT   (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "bytes", "id": "1", "type": "sum" }
     ],
     "query": " (domain:$select_domain) AND   (requestInterface:$select_api)  AND  (${entrance:raw})  NOT   (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应时间-平均时长",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "upstreamtime",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "type": "avg" }
     ],
     "query": "(domain:$select_domain) AND  (requestInterface:$select_api)  AND  (${entrance:raw})  NOT   (requestInterface:\"/\")",
     "timeField": "@timestamp"
    },
    {
     "alias": "responsetime",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "type": "avg" }
     ],
     "query": "(domain:$select_domain) AND  (requestInterface:$select_api)  AND  (${entrance:raw})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "平均响应时间(每日均值)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "responsetime",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "type": "avg" }
     ],
     "query": "(domain:$select_domain) AND  (requestInterface:$select_api)  AND  (${entrance:raw})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "错误状态码URI占比(TOP 5)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestInterface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "response",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " (domain:$select_domain)  AND  (${entrance:raw}) AND (response: [400 TO 504 ])  AND  (requestInterface:$select_api)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "错误状态码URI IP源占比(TOP 5)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestInterface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "clientip",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " (domain:$select_domain)  AND  (${entrance:raw}) AND (response: [400 TO 504 ])  AND  (requestInterface:$select_api)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求URI占比(TOP 5)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestInterface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " (domain:$select_domain) AND  (requestInterface:$select_api) AND  (${entrance:raw})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95百分位-按日统计",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "(domain:$select_domain)  AND   (requestInterface:$select_api) AND  (${entrance:raw})     NOT  (response:430)   NOT   (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95百分位",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "(domain:$select_domain)  AND   (requestInterface:$select_api) AND  (${entrance:raw})     NOT  (response:430)   NOT   (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "QPS、流量分析 接口:$select_api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "QPS TOP 10 URI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestInterface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api) NOT   (requestInterface:\"/\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "QPS TOP 10 用户源IP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "clientip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)  NOT   (requestInterface:\"/\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "流量 TOP 10 URI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestInterface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bytes", "id": "1", "type": "sum" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api) NOT   (requestInterface:\"/\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "流量 TOP 10 用户源IP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "clientip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "bytes", "id": "1", "type": "sum" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)  NOT   (requestInterface:\"/\")",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "响应时间分析 接口:$select_api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "平均响应时间",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "整体平均响应时间",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "responsetime", "id": "1", "type": "avg" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) NOT response: 499",
       "timeField": "@timestamp"
      },
      {
       "alias": "后端平均响应时间",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "upstreamtime", "id": "1", "type": "avg" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) NOT response: 499",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "响应时间区间占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "[0-20] ms",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) AND (responsetime:[0 TO 0.02])",
       "timeField": "@timestamp"
      },
      {
       "alias": "[20-40] ms",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api) AND (responsetime:{0.02 TO 0.04])",
       "timeField": "@timestamp"
      },
      {
       "alias": "[40-80] ms",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) AND (responsetime:{0.04 TO 0.08])",
       "timeField": "@timestamp"
      },
      {
       "alias": "[80+] ms",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) AND (responsetime:{0.08 TO *])",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "URI响应时间(TOP 10)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestInterface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "responsetime", "id": "1", "type": "avg" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "后端IP节点整体响应时间(TOP 10)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "upstreamaddr",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "responsetime", "id": "1", "type": "avg" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "可用性错误分布分析 接口:$select_api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "4XX状态码趋势",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "response",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:4*))",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "错误状态码趋势5xx4xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "response",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "(${entrance:raw}) AND (domain:$select_domain) AND (requestInterface:$select_api) AND (response:[401 TO 504]) AND NOT (response:430)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "4xx状态码URI占比(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestInterface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        {
         "field": "response",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:4*))",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "5xx状态码趋势",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "response",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:5*))",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "4xx状态码后端IP占比(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "upstreamaddr",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:4*))",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "5xx状态码的URI占比(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestInterface",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "response",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:5*))",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "5xx状态码的后端IP占比(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "upstreamaddr",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (${entrance:raw}) AND  (domain: $select_domain) AND (requestInterface:$select_api)  AND ( (response:5*))",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "流量分布 接口:$select_api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "运营商占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "geoip.isp_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api) ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "请求省份TOP 10",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "geoip.region_code",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)  NOT (geoip.region_name: \"\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "后端IP请求占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "upstreamaddr",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "客户端分析 接口:$select_api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "客户端UA(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "客户端IP(TOP 10)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "clientip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "客户端请求方式(TOP 5)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "verb",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND   (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "xff 真实IP来源",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "xff",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) +xff:[* TO *} -xff:-\n",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "ucar_IP请求占比",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ucar_ip",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "当前上游机器数量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 107 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "upstreamaddr", "id": "1", "settings": { "precision_threshold": "100" }, "type": "cardinality" }
       ],
       "query": "(domain:$select_domain) AND (requestInterface:$select_api) AND (upstreamaddr:10.*)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "reffer",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 116 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "referrer",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": " (domain:$select_domain) AND  (${entrance:raw}) AND    (requestInterface:$select_api) \nAND referrer:* \nNOT referrer:*lkcoffee* \nNOT referrer:*luckincoffee* \nNOT referrer:*servicewechat* \nNOT referrer:*alipay* \nNOT referrer:*cgbchina* \n\n ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}