{
 "title": "【LUCKY】LFE域名简版",
 "tags": [
  "全量细节查询",
  "15天数据",
  "LFE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "entrance",
    "label": "流量入口",
    "query": "Idc:logicA,Idc:logicB,provider:private,provider:huawei,provider:tencent,provider:nova"
   },
   {
    "name": "select_prod",
    "label": "产品线",
    "query": "{\"find\": \"terms\", \"field\": \"prod_type\", \"size\": 1000}"
   },
   {
    "name": "select_idc",
    "label": "数据中心",
    "query": "{\"find\": \"terms\", \"field\": \"provider\", \"orderBy\": \"doc_count\"}"
   },
   {
    "name": "select_domain",
    "label": "域名",
    "query": "{\"find\": \"terms\", \"field\": \"domain\",\"size\":10000}"
   },
   {
    "name": "select_api",
    "label": "API接口",
    "query": "{\"find\": \"terms\", \"field\": \"requestInterface\", \"query\": \"domain: $select_domain\", \"orderBy\": \"doc_count\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "$select_domain域名总览，具体信息请点击右上角；当前查看接口：(requestInterface:$select_api) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain)  AND  (requestInterface:$select_api)   NOT  (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "错误趋势",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "4xx",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain) AND (requestInterface:$select_api)   AND (response: [400 TO 499]) NOT  (requestInterface:\"/grafana/api/live/ws\") NOT  (requestInterface:\"/\")",
     "timeField": "@timestamp"
    },
    {
     "alias": "5xx",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain) AND (requestInterface:$select_api)   AND (response: [500 TO 599]) NOT  (requestInterface:\"/grafana/api/live/ws\")  NOT  (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应时间-平均时长",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "upstreamtime",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "type": "avg" }
     ],
     "query": "(domain:$select_domain)  AND  (requestInterface:$select_api)  ",
     "timeField": "@timestamp"
    },
    {
     "alias": "responsetime",
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responsetime", "id": "1", "type": "avg" }
     ],
     "query": "(domain:$select_domain)  AND  (requestInterface:$select_api)  ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "响应时间-响应时间95/99百分位",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "responsetime",
       "id": "1",
       "settings": {
        "percents": [
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "(domain:$select_domain)  AND  (requestInterface:$select_api)  ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "错误状态码URI占比(TOP 5)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestInterface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "response",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain) AND     (response: [400 TO 504 ]) AND  (requestInterface:$select_api) NOT  (requestInterface:\"/grafana/api/live/ws\")  NOT  (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求量URI占比(TOP 5)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestInterface",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(domain:$select_domain)  NOT  (requestInterface:\"/grafana/api/live/ws\")  NOT  (requestInterface:\"/\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "provider",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "bytes", "id": "1", "type": "sum" }
     ],
     "query": "(domain:$select_domain)  AND  (requestInterface:$select_api) ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}